name: Fong.ninja
favicon: null
layout_spectrum: 0.08735923236235976
typography_spectrum: 0.46370042976923287
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.20241400739178061
  lightness: 0.7277050176635385
  saturation: 0.16596164018847048
  rhythmicContrast: 0.6911174326669425
purpose: []
